add debian package
wirenboard/wb-modbus-ext-scanner pull request #1
Opened 2022-11-29 13:20 UTC by lostpoint-ru

add debian package

2022-11-29 13:25 UTC, sikmir commented on Makefile
> +	$(TPATH)$(CC) $(CFLAGS) $^ -o $(BIN_NAME)
а `TPATH` зачем нужен?

2022-11-29 14:33 UTC, lostpoint-ru commented on Makefile
> +	$(TPATH)$(CC) $(CFLAGS) $^ -o $(BIN_NAME)
Оно там было до меня :) TOOLCHAIN убрал чтобы ошибка сборки в cdeb исчезла.

2022-11-29 16:16 UTC, sikmir commented on Makefile
> +	$(TPATH)$(CC) $(CFLAGS) $^ -o $(BIN_NAME)
Может в Makefile еще добавить цель `install`?

2022-11-29 16:22 UTC, evgeny-boger commented on Makefile
> +	$(TPATH)$(CC) $(CFLAGS) $^ -o $(BIN_NAME)
мне наоборот с debian/install больше нравится, думаю нет смысла переделывать

2022-11-29 16:23 UTC, evgeny-boger commented on Makefile
> +	$(TPATH)$(CC) $(CFLAGS) $^ -o $(BIN_NAME)
TPATH надо поменять на более стандартный CROSS_COMPILE, который заполняет CC, если тот не задан. Ну или убрать к чёртовой матери, потому что задача была добавить автособранный пакет, а не вот это вот.

2022-11-29 16:38 UTC, sikmir approved these changes

2022-11-29 16:44 UTC, sikmir commented
LGTM, проверил сборку с `wbdev cdeb`.

2022-11-30 13:18 UTC, evgeny-boger commented
а через apt оно поставится? Ещё же наверное в wb-releases надо добавить

2022-11-30 13:18 UTC, evgeny-boger approved these changes

2022-11-30 13:24 UTC, webconn commented
> а через apt оно поставится? Ещё же наверное в wb-releases надо добавить

В тестинге поставится

2022-11-30 13:30 UTC, webconn requested changes
Ну раз уж делаем красиво

2022-11-30 13:30 UTC, webconn commented on Makefile
> +	$(TPATH)$(CC) $(CFLAGS) $^ -o $(BIN_NAME)
`CROSS_COMPILE`, кстати, не такой уж стандартный, в debian для этого `DEB_HOST_MULTIARCH` есть. А тут оказалось, что debhelper сам переопределил `CC` как надо и оно собралось. `TPATH` правда стоит убрать

В гайдлайне по дебианизации не хватает части про сборку multiarch, стоит добавить при случае.

2022-11-30 13:51 UTC, lostpoint-ru commented on debian/control
> +Description: Scanner utility for extended
Можно, но тогда Lintian при сборке будет валиться с ошибкой 
E: wb-modbus-ext-scanner: extended-description-is-empty

2022-11-30 14:53 UTC, webconn approved these changes

2022-11-30 15:02 UTC, merged